### ISSUE TITLE
Update Software Icon to Match README Logo

### ISSUE THREAD

**Issue by 666ghj** [LinJHS/AntiRec#1]
Your software icon is still the default icon, I see your README has a logo, you can use it as your icon :)

**Comment by LinJHS** [comment]
Oh! Thank you for your feedback. I will address this issue in the next version.

**Comment by 666ghj** [comment]
All right, love you😘

**Comment by LinJHS** [comment]
The issue has been resolved, you can check https://github.com/LinJHS/AntiRec/releases/tag/v1.2.0, and I'll close this issue if there are no other issues.

**Comment by 666ghj** [comment]
Thank you for the update! I’ve checked the new release, and the icon now matches the README logo. Everything looks great! 🎉
