### ISSUE TITLE
[BUG] Synchronise against Scrambler Library (同步对抗扰动库) is not available!

### ISSUE THREAD

**Issue by Ashfudie** [LinJHS/AntiRec#15]
**Describe the bug**
When I click on "Synchronise against Scrambler Library (同步对抗扰动库)", I find that the page shows 404

**To Reproduce**
1. Go to Home Page
2. Click on '同步对抗扰动库'

**Expected behavior**
Synchronize against Scrambler Library

**Screenshots**
![微信图片_20241223084018](https://github.com/user-attachments/assets/1c716738-c43f-4ca3-97c7-6db732d0f3fb)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version Until Dec 11, 2024 Commit 2bbe7f4d6141045a1ee751c789953dfc8235aabe

**Comment by LinJHS** [comment]
I've received your feedback and I'll fix the problem as soon as possible. I'm sorry for any distress this may have caused you.

**Comment by LinJHS** [comment]
This was fixed in the latest release: https://github.com/LinJHS/AntiRec/releases/tag/v1.2.1
You can check to see if the issue still occurs. Thank you very much for your feedback!

**Comment by Ashfudie** [comment]
OK, this issue is fixed, thank you
