### ISSUE TITLE
Requesting a macOS version

### ISSUE THREAD

**Issue by lt0715** [LinJHS/AntiRec#3]
The provided releases do not include a macOS version. Could you please let us know when a macOS version of the application will be available?

**Comment by LinJHS** [comment]
I don't currently have a Mac, but if I can borrow one for testing, I will consider supporting macOS.

**Comment by LinJHS** [comment]
The issue has been resolved, you can check https://github.com/LinJHS/AntiRec/releases/tag/v1.2.0, and I'll close this issue if there are no other issues.

**Comment by lt0715** [comment]
Okay, thank you
